stages:
  - lint
  - deploy

lint_javascript:
  stage: lint
  image: node:latest
  script:
    - npm install -g jshint
    - jshint script.js

deploy_to_server:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - scp -r public/* admin1337@vaporwave.fr:/var/www/html/
  only:
    - master